Repository asos-craigmorten/superoak, pull requests merged in 2020-12, with the labels that each got.

#11 [#10] Upgrade to superdeno 2.4.0, expect 0.2.6 and std 0.79.0
  .github/CHANGELOG.md
  .github/CONTRIBUTING.md
  .github/workflows/publish-docs.yml
  .github/workflows/publish-egg.yml
  .github/workflows/test.yml
  Makefile
  README.md
  deps.ts
  docs/index.html
  egg.json
  lock.json
  mod.ts
  src/superoak.ts
  test/deps.ts
  test/superoak.test.ts
  version.ts
Labels: bug

#12 [NO-ISSUE] Upgrade to superdeno 2.4.1
  .github/CHANGELOG.md
  README.md
  deps.ts
  docs/index.html
  egg.json
  lock.json
  version.ts
Labels: bug, dependencies

#15 [NO-ISSUE] Deno 1.6.0
  .github/CHANGELOG.md
  .github/workflows/publish-docs.yml
  .github/workflows/publish-egg.yml
  .github/workflows/test.yml
  README.md
  deps.ts
  docs/index.html
  egg.json
  lock.json
  test/deps.ts
  test/superoak.test.ts
  test/utils.ts
  version.ts
Labels: chore, dependencies

#16 [NO-ISSUE] Support redirects API
  .github/CHANGELOG.md
  README.md
  deps.ts
  docs/index.html
  egg.json
  lock.json
  test/superoak.test.ts
  version.ts
Labels: feature

#14 [#13] Update README.md add FAQs section
  README.md
Labels: documentation
